### ISSUE TITLE
RuntimeError: Error during generate_quantities retcodes=[3221225477]

### ISSUE THREAD

**Issue by gregorp90** [stan-dev/cmdstan#1046]
#### Summary:
Hi all, I'm trying to use the `generate_quantities` function of the CmdStanModel class. The model compiles, however, once I run it I get some runtime errors that are not very helpful in debugging.

#### Description:
I'm running hierarchical stacking on relatively large data sets, so I would like to use an already sampled model to generate predictions. I tried running the code described here: https://mc-stan.org/cmdstanpy/examples/Run%20Generated%20Quantities.html, which works perfectly fine. However, once I try to apply it to my problem, I get the following error:
```
new_quantities = hstack_ppc_model.generate_quantities(data=hstack_data, mcmc_sample=hstack_fit)
INFO:cmdstanpy:start chain 1
INFO:cmdstanpy:finish chain 1
ERROR:cmdstanpy:Chain 1 processing error, non-zero return code 3221225477
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c21edc63150d>", line 1, in <module>
    new_quantities = hstack_ppc_model.generate_quantities(data=hstack_data, mcmc_sample=hstack_fit)
  File "C:\Anaconda3\lib\site-packages\cmdstanpy\model.py", line 990, in generate_quantities
    raise RuntimeError(msg)
RuntimeError: Error during generate_quantities:
Command and output files:
RunSet: chains=1
 cmd:
	['E:/shared_files_e/Gregor/gq-problem/hstack_ppc.exe', 'id=1', 'random', 'seed=8051', 'data', 'file=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\kk9sd6ws.json', 'output', 'file=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\hstack_ppc-202109201615-1-baz2k23v.csv', 'method=generate_quantities', 'fitted_params=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\hstack-202109201615-1-i2f4k2ei.csv']
 retcodes=[3221225477]
 csv_files:
	C:\Users\Gregor\AppData\Local\Temp\tmp101s6tue\hstack_ppc-202109201615-1-baz2k23v.csv
 console_msgs:
	C:\Users\Gregor\AppData\Local\Temp\tmp101s6tue\hstack_ppc-202109201615-1-baz2k23v-stdout.txt
```

I am unable to decipher this error message. The only thing that changed from the Bernoulli example is that _hstack.stan_ model uses matrices and a transformed data block. I'm attaching a minimal example. I also tried running `sample` for the model with generated quantities (_hstack_ppc.stan_) and it works, so the problem is only in running `generated_quantities` with an already sampled model. Hopefully, I'm not missing something obvious.

As a workaround I could generate new quantities outside of Stan, however, I would prefer using Stan if possible.

#### Additional Information:
This happened on two separate machines with versions 0.9.76 and 0.9.77 of cmdstanpy. Both machines run Windows 10.

#### Current Version
0.9.76/0.9.77

#### Attachments
[gq-problem.zip](https://github.com/stan-dev/cmdstanpy/files/7196445/gq-problem.zip)

**Comment by WardBrian** [comment]
Hi @gregorp90 - I've moved your issue to the cmdstan repo where hopefully you can get a better answer

**Comment by gregorp90** [comment]
Hi @WardBrian, thank you! In the meantime, I'll just compute the generated quantities in Python using the samples.
