### ISSUE TITLE
install_cmdstan fails with "No such file or directory" on GNU/Linux

### ISSUE THREAD

**Issue by cpbl** [stan-dev/cmdstan#1166]
#### Summary:
I'm trying to install cmdstanpy on a new machine (Ubuntu 22.04.2 LTS).  I've done the pip part, but the cmdstan installation fails:

#### Description:

```
$ install_cmdstan
Installing CmdStan version: 2.32.2
Install directory: /home/meuser/.cmdstan
Downloading CmdStan version 2.32.2
Download successful, file: /tmp/tmp_az3x6n8
Extracting distribution
Unpacked download as cmdstan-2.32.2
Building version cmdstan-2.32.2, may take several minutes, depending on your system.
Traceback (most recent call last):
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 282, in build
    do_command(cmd, fd_out=None)
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/utils/command.py", line 76, in do_command
    raise RuntimeError(msg)
RuntimeError: Command ['make', 'build', '-j1']
        error during processing No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/bin/install_cmdstan", line 8, in <module>
    sys.exit(__main__())
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 668, in __main__
    run_install(InstallationSettings(**args))
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 602, in run_install
    install_version(
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 422, in install_version
    build(verbose, progress=progress, cores=cores)
  File "/home/meuser/papers/mypaper/bin/project_cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 286, in build
    raise CmdStanInstallError(f'Command "make build" failed\n{str(e)}')
cmdstanpy.install_cmdstan.CmdStanInstallError: Command "make build" failed
Command ['make', 'build', '-j1']
        error during processing No such file or directory
```

#### Current Version:
v2.32.2

**Comment by WardBrian** [comment]
Can you share the output of `make —version` and `gcc —version`?

**Comment by cpbl** [comment]
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by WardBrian** [comment]
Can you run `install_cmdstan --verbose` and include the output?

**Comment by WardBrian** [comment]
I'm closing this due to lack of activity, please re-open if this issue is still occurring.
